### ISSUE TITLE
In the post popup, 12pm and 12am are inverted

### ISSUE THREAD

**Issue by cedricb12** [Aymanhki/Epoch#311]
when i select 12pm it is posted at 12am and vice versa

**Comment by cedricb12** [comment]
after googling I'm not sure if this is actually a bug or if my understanding of 12 am/pm is wrong. So im fine closing this if someone else is

**Comment by Aymanhki** [comment]
I tried to make it more clear in the pr, if you think it's good close this issue, if not, let me know what to change.
